services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft_server
    restart: unless-stopped

    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"

      TYPE: PAPER
      VERSION: LATEST
      MEMORY: 4G
      TZ: America/Fortaleza

      MOTD: "CAIODEV SERVER"
      MODE: survival
      DIFFICULTY: hard
      ONLINE_MODE: "TRUE"

      SEED: "6944174826991112"

      PLUGINS: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot,https://github.com/NEZNAMY/TAB/releases/download/6.0.3/TAB.v6.0.3.-.Vanilla.jar"

      ENABLE_ROLLING_LOGS: "true"

    volumes:
      - /srv/games/minecraft/data:/data

    networks:
      - game_network
    
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      N8N_SECURE_COOKIE: "false"
      TZ: America/Fortaleza

      # Altere para um usuário e senha fortes
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "resenha1234"

      # Opcional, mas recomendado
      N8N_HOST: "192.168.0.46"
      N8N_PORT: "5678"
      N8N_PROTOCOL: "http"

    volumes:
      - /srv/docker/n8n/data:/home/node/.n8n

    networks:
      - game_network

networks:
  game_network:
    driver: bridge